export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const EVENTS_FETCH_REQUEST = 'EVENTS_FETCH_REQUEST';
export const EVENTS_FETCH_SUCCESS = 'EVENTS_FETCH_SUCCESS';
export const EVENTS_FETCH_FAILURE = 'EVENTS_FETCH_FAILURE';

export const EVENTS_REFRESH_REQUEST = 'EVENTS_REFRESH_REQUEST';
export const EVENTS_REFRESH_SUCCESS = 'EVENTS_REFRESH_SUCCESS';
export const EVENTS_REFRESH_FAILURE = 'EVENTS_REFRESH_FAILURE';

export const EVENT_FETCH_REQUEST = 'EVENT_FETCH_REQUEST';
export const EVENT_FETCH_SUCCESS = 'EVENT_FETCH_SUCCESS';
export const EVENT_FETCH_FAILURE = 'EVENT_FETCH_FAILURE';

export const EVENT_PARTICIPANTS_FETCH_REQUEST = 'EVENT_PARTICIPANTS_FETCH_REQUEST';
export const EVENT_PARTICIPANTS_FETCH_SUCCESS = 'EVENT_PARTICIPANTS_FETCH_SUCCESS';
export const EVENT_PARTICIPANTS_FETCH_FAILURE = 'EVENT_PARTICIPANTS_FETCH_FAILURE';
